# Generated by Django 3.2.9 on 2021-11-20 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='aggregator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='using', to='track.aggregator'),
        ),
        migrations.AddField(
            model_name='route',
            name='tractor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executing', to='track.tractor'),
        ),
    ]
