# Generated by Django 3.2.9 on 2021-11-19 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_rename_upload_tractortrack_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='tractortrack',
            name='self_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='track.tractortrack'),
        ),
    ]
