# Generated by Django 3.2.9 on 2021-11-20 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_auto_20211120_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='tractortrack',
            name='shortdesc',
            field=models.CharField(default='Cultivation of Example', max_length=100),
            preserve_default=False,
        ),
    ]
